[server]
headless = true
address = "0.0.0.0"
port = 8501
maxUploadSize = 5

[theme]
base="light"
primaryColor="#eb5d0c"

[theme]
base="dark"
primaryColor="#eb5d0c"
backgroundColor="#353535"
secondaryBackgroundColor="#595959"
textColor="#ffffff"
