[server]
headless = true
address = "0.0.0.0"
port = 8501
maxUploadSize = 5

[theme]
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
primaryColor = "#eb5d0c"
