[database]
url = "postgresql://appuser:Booklife01@192.168.1.128:5433/appdb"
[admin]
error_log_password = "nan"
[passwords]
"Bethany Latham" = "password"
"Noah Leatherland" = "password"
"Charis Mather" = "password"
"Drue Rintoul" = "password"
"Amy Li" = "password"
"Amelia Harris" = "password"
"Ker Ker Lee" = "password"
"Jasmine Pointer" = "password"
"Rob Delph" = "password"
"admin" = "admin"
